### ISSUE TITLE
可能错误的链接

### ISSUE THREAD

**Issue by thawk** [Cpp-Club/Cxx_HOPL4_zh#16]
发现一些链接可能是不正确的。不过本项目使用的转换脚本没有放在github上，因此不能确认是否真的有问题：

* 有两个链接出现了两种写法，涉及要不要加上一个``-``。应该有一种是错误的：

  ```
  04.md:52:(#41-c11并发支持)
  11.md:26:(04.md#41-c11-并发支持)
  ```
  
  ```
  04.md:53:(#42-c11简化使用)
  05.md:124:(04.md#42-c11-简化使用)
  06.md:696:(04.md#42-c11-简化使用)
  09.md:12:(04.md#42-c11-简化使用)
  09.md:12:(04.md#42-c11-简化使用)
  11.md:179:(04.md#42-c11-简化使用)
  ```

* ``9.3.1``的标l题是``9.3.1 模块``，而链接使用的是``#931-modules``，应该是有问题的

* ``9.3.1``的标题是``9.3.4 &lt;=>``，链接使用的是``#934-lt``，不确实是否正确

**Comment by adah1972** [comment]
多谢。有标题修改后漏重新转换的，也有转换错误的（&lt;=> 那个）。
