### ISSUE TITLE
03.md 开头处的 ISO/IEC JTC1/SC2/WG21 应该改成 SC22

### ISSUE THREAD

**Issue by hebohang** [Cpp-Club/Cxx_HOPL4_zh#34]
03.md 开头处的

> 国际 C++ 标准委员会正式名称为 ISO/IEC JTC1/SC2/WG21

应更正为：

> 国际 C++ 标准委员会正式名称为 ISO/IEC JTC1/SC22/WG21

**Comment by adah1972** [comment]
谢谢。
