### ISSUE TITLE
一处笔误

### ISSUE THREAD

**Issue by zhurui37** [Cpp-Club/Cxx_HOPL4_zh#50]
在第二章中：
”开发转向其他语言的另一个重要原因是，模板提供的接口的灵活性使得使用所有 C++ 特性并提供稳定的 ABI 变得极其困难：可以灵活，也可以提供稳定的二进制接口，但大多数组织都做不到两者兼顾。我认为人们之所以需要 C++ 编写的程序提供 C、Java、C# 之类的接口，这是个促成因素。C++ 的 ABI 稳定性是一个真正的技术难题，尤其是因为 C++ 标准必须独立于平台。“

提供稳定的 **ABI** 变得极其困难，**ABI**是否应该是**API**

**Comment by adah1972** [comment]
不是。这里就是 ABI。
