### ISSUE TITLE
11.4 章节，Given a direction and ...翻译貌似不太合理

### ISSUE THREAD

**Issue by lijie-jiang** [Cpp-Club/Cxx_HOPL4_zh#51]
`Given a direction and a set of principles, a language can grow based on feedback, user experience, experiments, and theory as tools. This is good engineering as opposed to unprincipled pragmatism or dogmatic idealism.`
"...和作为工具的理论成长“貌似不妥，建议修改为：
”...一种语言可以在反馈、用户经验、实验和理论作为工具的基础之上成长...“

**Comment by adah1972** [comment]
原来翻译得确实有点拗口。我调整了一下，改成了意译。
